[phases.setup]
nixPkgs = ["python311Packages.pip", "python311", "gcc"]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[start]
cmd = "gunicorn -w 4 -b 0.0.0.0:8080 main:app"
