[phases.setup]
nixPkgs = ["python311Full"]

[phases.install]
cmds = ["python3.11 -m pip install --upgrade pip", "pip install -r requirements.txt"]

[start]
cmd = "gunicorn -w 4 -b 0.0.0.0:8080 main:app"
